
# This file was *autogenerated* from the file Cpb01_1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p0 = RealNumber('0.0'); _sage_const_1300 = Integer(1300)
from sage.graphs.graph_plot import GraphPlot
G = DiGraph({"Tirage":["P P","P I","I I"]})
G.add_edges([("Tirage","P P",r'$\frac{1}{6}$ ')])
#G.set_latex_options(
#    edge_color = 'green'
#)
GP = GraphPlot(G,{'vertex_size' : _sage_const_1300 ,
                  'edge_thickness' : _sage_const_0p0 ,
                  'edge_labels' : True , 
                  'edge_style' : '-',
                  'prog' : "dot"}
               )
P = GP.plot()
P.save('Cpb01_1.pdf')

